sudo: required

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - SIMPLESAMLPHP_VERSION=1.17.*
  
matrix:
  include:
    - php: 5.6
      env: SIMPLESAMLPHP_VERSION=dev-master
    - php: 7.0
      env: SIMPLESAMLPHP_VERSION=dev-master
    - php: 7.1
      env: SIMPLESAMLPHP_VERSION=dev-master
    - php: 7.2
      env: SIMPLESAMLPHP_VERSION=dev-master
    - php: 7.3
      env: SIMPLESAMLPHP_VERSION=dev-master
  allow_failures:
    # We can't always keep up with changes in SSP-master
    - env: SIMPLESAMLPHP_VERSION=dev-master

before_script:
  - pecl install krb5
  - sudo apt-get install stunnel4 apache2
  - openssl req -x509 -newkey rsa:1024 -nodes -keyout tests/files/webserver.key -out tests/files/webserver.crt -days 1 -subj '/CN=localhost'; cat tests/files/webserver.key tests/files/webserver.crt > tests/files/webserver.pem
  - php -S localhost:8080 &
  - export WEBPID=$!
  - if [[ "$TRAVIS_PHP_VERSION" < "5.6" ]]; then sudo stunnel3 -p tests/files/webserver.pem -d 443 -r 8080; else sudo stunnel4 tests/files/stunnel.conf; fi
  - mkdir /tmp/testdisk; sudo mount -t tmpfs -o size=100k tmpfs /tmp/testdisk; sudo chmod -R 777 /tmp/testdisk
  - phpenv config-add tests/files/myphp.ini
  - composer require "simplesamlphp/simplesamlphp:${SIMPLESAMLPHP_VERSION}" --no-update
  - composer update --no-interaction
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then composer require --dev vimeo/psalm:1.1.9; fi

script:
  - bin/check-syntax.sh
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/phpunit/phpunit/phpunit; else php vendor/phpunit/phpunit/phpunit --no-coverage; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then vendor/bin/psalm; fi

after_success:
  - sudo umount /tmp/testdisk; rm -rf /tmp/testdisk
  - kill -kill $WEBPID
  # Codecov, need to edit bash uploader for incorrect TRAVIS_PYTHON_VERSION environment variable matching, at least until codecov/codecov-bash#133 is resolved
  - curl -s https://codecov.io/bash > .codecov
  - sed -i -e 's/TRAVIS_.*_VERSION/^TRAVIS_.*_VERSION=/' .codecov
  - chmod +x .codecov
  - if [[ $TRAVIS_PHP_VERSION == "5.6" ]]; then ./.codecov -X gcov; fi
  # - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then bash <(curl -s https://codecov.io/bash); fi
